In [3]:
import numpy as np
import scipy 
import scipy.linalg
import matplotlib.pyplot as plt
from scipy.integrate import quad
from tqdm import tqdm,trange

|  | min   | max  | average  | stdev  |
|---------------------|---|---|---|---|
| $\sigma_{i,\infty}^2$ | 0.00060%  | 0.05150% | 0.01770%  | 0.01440% |
| $\alpha_i$  | 0.0329  | 0.0955 | 0.0622 | 0.0242 |
| $\beta_i$  | 0.8855  | 0.9656  | 0.9306 | 0.0271 |
| $\omega_i$  | 0.0000032% | 0.0004320% | 0.0001350%| 0.0001370% |
| $\rho_{i, j}$  | -22%  | 82%  | 10& | 22% |
| $p_{max,i}$  | 1.83  |5.72 | 3.34 | 1.22 |
| $t_{1/2,i}$  | 36.21 | 437.17 | 135.78 | 98.52 |

$$r_t=D_t\Gamma^{1/2}\eta_t=D_t\tilde{\eta_t},$$ $$V_t=D_t\Gamma D_t,$$
$$\sigma_{i,t}^2 = \omega_{i,t}+\alpha_ir_{i,t-1}^2+\beta_i\alpha_{i,t-1}^2=(1, r_{i,t-1}^2, \sigma_{i,t-1}^2)\theta_i, \, \theta_i=(\omega_i, \alpha_i, \beta_i)^T$$

### Robins Monro with $\theta$ constant

In [4]:
theta = np.array([1.35e-6, 0.0622, 0.9306])
d = 3

In [5]:
def R_simulator(R0, sigma2_0, theta, Gamma):
    ones = np.ones((d,1))
    g = np.hstack((ones, R0**2, sigma2_0))
    sigma2 = g.dot(theta)
    D = np.diag(np.sqrt(sigma2))
    eta = np.sqrt(Gamma).dot(np.random.randn(d))  
    return D.dot(eta)

In [6]:
np.hstack((np.ones((d,1)),np.ones((d,1))))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
from scipy.stats import random_correlation

In [27]:
np.random.seed(123)
corr = np.diag(np.ones(d))
for i in range(d):
    for j in range(i+1, d):
        corr[i, j] = corr[j, i] = np.random.uniform(-0.2, 0.8)
corr

array([[1.        , 0.49646919, 0.08613933],
       [0.49646919, 1.        , 0.02685145],
       [0.08613933, 0.02685145, 1.        ]])

In [28]:
import scipy.linalg
e, v = scipy.linalg.eigh(corr)
e

array([0.49997036, 0.99097736, 1.50905228])