In [1]:
import numpy as np
import scipy.special as sp
from scipy.integrate import quad

In [5]:
def Legendre_B(a, b, n):
    """
    generate a normalized Legendre basis in the interval [a, b]
    n is the number of the Legendre basis needed
    """
    delta = b-a
    LB = [sp.legendre(i) for i in range(n)]
    new = []
    for i in range(n):
        z = lambda x: np.sqrt((2*i+1)/delta)*LB[i]((2*x-a-b)/(b-a))
#         z = lambda x: LB[i](x)
#         print(z(rho))
        new.append(z)
    return new

In [6]:
lb = 

SyntaxError: invalid syntax (<ipython-input-6-60bb60ba5f5d>, line 1)

In [7]:
rho = 0.35
r_min, r_max = 0.3,0.5

In [8]:
lb = Legendre_B(r_min,r_max,5)

In [9]:
lb

[<function __main__.Legendre_B.<locals>.<lambda>(x)>,
 <function __main__.Legendre_B.<locals>.<lambda>(x)>,
 <function __main__.Legendre_B.<locals>.<lambda>(x)>,
 <function __main__.Legendre_B.<locals>.<lambda>(x)>,
 <function __main__.Legendre_B.<locals>.<lambda>(x)>]

In [10]:
for i in range(5):
    print(lb[i](rho))

-1.9390901992380998
-1.9390901992380998
-1.9390901992380998
-1.9390901992380998
-1.9390901992380998


In [11]:
lb[2]

<function __main__.Legendre_B.<locals>.<lambda>(x)>

In [12]:
 LB = [np.sqrt((2*i+1)/0.2)*sp.legendre(i) for i in range(5)]

In [13]:
LB

[array([2.23606798]),
 array([3.87298335, 0.        ]),
 array([ 7.5,  0. , -2.5]),
 array([14.79019946,  0.        , -8.87411967,  0.        ]),
 array([ 2.93483922e+01,  3.25832608e-15, -2.51557647e+01,  1.62916304e-15,
         2.51557647e+00])]

In [22]:
LB = [np.polynomial.legendre.Legendre.basis(deg=i) for i in range(5)]

In [15]:
LB[2](rho)

-0.31625000000000003

In [49]:
a = 0.3
b = 0.5
delta = b-a
test = {}
for i in range(5):
#     func = lambda x: (np.sqrt((2*i+1)/delta)*LB[i]((2*x-a-b)/(b-a)))#*(np.sqrt((2*i-1)/delta)*LB[i-1]((2*x-a-b)/(b-a)))
    test[str(i)] = (lambda x: (np.sqrt((2*i+1)/delta)*LB[i]((2*x-a-b)/(b-a))))
#     print(quad(func,0.3,0.5))

In [31]:
LL = [lambda x:np.sqrt((2*i+1)/delta)*np.polynomial.legendre.Legendre.basis(deg=i)((2*x-a-b)/(b-a)) for i in range(5)]

In [32]:
LL[1](0.35)

-1.9390901992381

In [53]:
test[0]

KeyError: 0

In [74]:
for i in range(5):
    print(test[i](rho))

2.23606797749979
-1.936491673103709
-0.6249999999999991
2.588284905106082
-1.9390901992381


In [65]:
test[0](0.35)

TypeError: <lambda>() takes 0 positional arguments but 1 was given

In [56]:
def one_Legendre_basis(x,i):
    return lambda :np.sqrt((2*i+1)/delta)*np.polynomial.legendre.Legendre.basis(deg=i)((2*x-a-b)/(b-a))

In [59]:
def Legendre_B(a, b, n):
    """
    generate a normalized Legendre basis in the interval [a, b]
    n is the number of the Legendre basis needed
    """
    delta = b-a
    store = []
    for i in range(n):
        store.append(one_Legendre_basis(x,i))
    return store

In [73]:
test = Legendre_B(a,b,5)

In [75]:
def Legendre_B(a, b, n):
    """
    generate a normalized Legendre basis in the interval [a, b]
    n is the number of the Legendre basis needed
    """
    delta = b-a
    LB = [np.sqrt((2*i+1)/delta)*np.polynomial.legendre.Legendre.basis(deg=i) for i in range(n)]
    new = []
    for i in range(n):
        z = lambda x,i=i: LB[i]((2*x-a-b)/(b-a))
        new.append(z)
    return new

In [76]:
test = Legendre_B(a,b,5)

In [77]:
for i in range(5):
    print(test[i](rho))

2.23606797749979
-1.936491673103709
-0.6249999999999991
2.588284905106082
-1.9390901992381


In [82]:
for i in range(4):
    func = lambda x: test[i](x)*test[i+1](x)
    print(quad(func,a,b)[0])

4.706213772282515e-16
1.2442703165276746e-15
2.2515455273140526e-15
3.4384483129952753e-15
